[package]
name = "a-streaming-service"
version = "0.1.0"
authors = ["Josh <jo3f@mtmail.mtsu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]